# TensorFlow Serving image with model baked in from a provided tarball in build context.
FROM tensorflow/serving:latest

ARG MODEL_TAR=model.tar.gz
ENV MODEL_NAME=clothsnap

# Copy the model tarball from build context and unpack to /models/clothsnap/1
COPY ${MODEL_TAR} /tmp/model.tar.gz

RUN mkdir -p /models/${MODEL_NAME}/1 /tmp/model && \
    tar -xzf /tmp/model.tar.gz -C /tmp/model && \
    cp -a /tmp/model/tf_serving_ready_model/. /models/${MODEL_NAME}/1/ && \
    rm -rf /tmp/model /tmp/model.tar.gz

EXPOSE 8501

ENTRYPOINT ["/usr/bin/tf_serving_entrypoint.sh"]
