version: "3.8"

services:
  tf-serving:
    image: ghcr.io/zipingliu-jokerh/clothsnap-tfserving:latest
    container_name: clothsnap-tf-serving
    ports:
      - "8501:8501" # optional to expose publicly; can remove in prod
    restart: unless-stopped

  flask:
    image: ghcr.io/zipingliu-jokerh/clothsnap-flask:latest
    container_name: clothsnap-flask
    environment:
      - CLOTHSNAP_TF_URL=http://tf-serving:8501/v1/models/clothsnap:predict
      - PORT=5001
    depends_on:
      - tf-serving
    ports:
      - "5001:5001"
    restart: unless-stopped
