name: Build and Push Images

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write       # for AWS OIDC
  packages: write       # for GHCR push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FLASK: clothsnap-flask
  IMAGE_NAME_TFSERVING: clothsnap-tfserving

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Docker login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build Flask image
        run: |
          docker build \
            -f Dockerfile.flask \
            -t $REGISTRY/${IMAGE_NAME_FLASK}:latest \
            .

      - name: Build TF Serving image (model baked in)
        run: |
          docker build \
            -f Dockerfile.tfserving \
            --build-arg MODEL_URL=${{ vars.MODEL_URL }} \
            -t $REGISTRY/${IMAGE_NAME_TFSERVING}:latest \
            .

      - name: Push images
        run: |
          docker push $REGISTRY/${IMAGE_NAME_FLASK}:latest
          docker push $REGISTRY/${IMAGE_NAME_TFSERVING}:latest
